import * as React from 'react';

export const en = {
  newsHeaderName: "Swabhimani News",
  shopHeaderName: "Swabhimani Shop",
  Home: "Home",
  Setting: "Setting",
  Find: "Search",
  TabNews:"News",
  TabShop:"Shop",
  CreateNews:"Create News", 
  HeadLineofNews : "       Please enter headline of your news                           ",
  ContentofNews  : "       Please enter content of your news                            ",

};

export const mr = {
  newsHeaderName: "स्वाभिमानी न्यूस",
  shopHeaderName: "स्वाभिमानी खरेदी",
  Home: "होम",
  Setting: "सेटिंग",
  Find: "शोध",
  TabNews:"न्यूस",
  TabShop:"खरेदी",
  CreateNews:"बातम्या तयार करा",
  HeadLineofNews : "            कृपया आपल्या बातमीची शीर्षके लिहा                                 ",
  ContentofNews :  "            कृपया आपल्या बातमी लिहा                                       ",

};

export const authScreenLabels = {
  en: {
    'BacktoSignIn':'BacktoSignIn',
    'Change':'Change',
    'ChangePassword':'ChangePassword',
    'Verificationcode':'Verificationcode',
    'Entercode':'Entercode',
    'ConfirmationCode':'ConfirmationCode',
    'Enteryourcode':'Enteryourcode',
    'ConfirmSignup':'ConfirmSignup',
    'Lostyourcode?':'Lostyourcode?',
    'ResendCode':'ResendCode',
    'Confirm':'Confirm',
    'ConfirmSMSCode':'ConfirmSMSCode',
    'ConfirmTOTPCode':'ConfirmTOTPCode',
    'Confirm':'Confirm',
    'Createaccount':'Createaccount',
    'EmailAddress*':'EmailAddress*',
    'amplify@example.com':'amplify@example.com',
    'Forgotyourpassword?':'Forgotyourpassword?',
    'Lessthantwomfatypesavailable':'Lessthantwomfatypesavailable',
    'Newpassword':'Newpassword',
    'Enteryournewpassword':'Enteryournewpassword',
    'Noaccount?':'Noaccount?',
    'Password*':'Password*',
    'Enteryourpassword':'Enteryourpassword',
    'PhoneNumber*':'PhoneNumber*',
    '(555) 555-1212':'(555)555-1212',
    'qrcode':'qrcode',
    'Resetpassword':'Resetpassword',
    'Resetyourpassword':'Resetyourpassword',
    'SelectMFAType':'SelectMFAType',
    'Verify':'Verify',
    'SendCode':'SendCode',
    'TOTPneedstobeconfigured':'TOTPneedstobeconfigured',
    'SignIn':'SignIn',
    'Signintoyouraccount':'Signintoyouraccount',
    'Signin':'Signin',
    'SigninwithAmazon':'SigninwithAmazon',
    'SigninwithAuth0':'SigninwithAuth0',
    'SigninwithAWS':'SigninwithAWS',
    'SigninwithFacebook':'SigninwithFacebook',
    'SigninwithGoogle':'SigninwithGoogle',
    'SignOut':'SignOut',
    'Email':'Email',
    'Haveanaccount?':'Haveanaccount?',
    'Createanewaccount':'Createanewaccount',
    'Password':'Password',
    'CreateAccount':'CreateAccount',
    'Username':'Username',
    'Success!YourMFATypeisnow':'Success!YourMFATypeisnow',
    'Scanthenenterverificationcode':'Scanthenenterverificationcode',
    'EnterSecurityCode':'EnterSecurityCode',
    'TOTPSetuphasfailed':'TOTPSetuphasfailed',
    'VerifySecurityToken':'VerifySecurityToken',
    'SetupTOTPsuccessfully!':'SetupTOTPsuccessfully!',
    'Failed!UnabletoconfigureMFAatthistime':'Failed!UnabletoconfigureMFAatthistime',
    'Username*':'Username*',
    'Enteryourusername':'Enteryourusername',
    'Email':'Email',
    'Accountrecoveryrequiresverifiedcontactinformation':'Accountrecoveryrequiresverifiedcontactinformation',
    'PhoneNumber':'PhoneNumber',
    'Submit':'Submit',
  }
};

export const LocalizationContext = React.createContext();
